# Use a Node.js base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Command to run the app using nodemon
CMD ["npm", "run", "watch-autoscaler"]
