apiVersion: v1
kind: Service
metadata:
  name: opti-k8s-autoscaler
spec:
  type: NodePort
  selector:
    app: opti-k8s-autoscaler
  ports:
    - port: 4001
      targetPort: 4001
      nodePort: 30009  # Optional: specify a node port in the range 30000-32767 or leave it blank for Kubernetes to auto-assign
