apiVersion: apps/v1
kind: Deployment
metadata:
  name: opti-k8s-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opti-k8s-scheduler
  template:
    metadata:
      labels:
        app: opti-k8s-scheduler
    spec:
      containers:
      - name: opti-k8s-scheduler
        image: opti-k8s-scheduler:latest  # Replace with your image name and tag
        ports:
        - containerPort: 4000