apiVersion: v1
kind: Service
metadata:
  name: opti-k8s-scheduler
spec:
  type: NodePort
  selector:
    app: opti-k8s-scheduler
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30008  # Optional: specify a node port in the range 30000-32767 or leave it blank for Kubernetes to auto-assign
